# Generated by Django 4.2.2 on 2023-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('user', models.CharField(max_length=255, verbose_name='user')),
                ('department', models.CharField(max_length=255, verbose_name='department')),
                ('software', models.CharField(max_length=255, verbose_name='software')),
                ('seats', models.IntegerField(verbose_name='seats')),
                ('amount', models.FloatField(verbose_name='amount')),
            ],
        ),
    ]
